language: node_js
node_js:
  - lts/*
  - stable

# wait until after all node.js versions pass before deploying
# https://docs.travis-ci.com/user/build-stages/deploy-npm/

stages:
  - test
  - name: deploy
    if: tag IS present AND repo = 'nfriedly/express-slow-down'

jobs:
  include:
    - stage: deploy
      node_js: stable
      script: skip
      deploy:
        provider: npm
        email: nathan@nfriedly.com
        api_key:
          secure:
            "P2UtyQkROJotlvJyX4R+ZU6dRe4aOB7xLWDu+QzStpwVNV5czY2x9M2yWHKS4EnthM5f+9LhytiyWI3XbGKwsYzUX8kgIlkh98RFOVJ51dXoGj68FBuDHou3wold9g7n3zJgUoJyTDodzS+aMbhl/omuVROWqnn66cuC6IGP6jVsdnlZ5fxrMY1uGszpNXPzetxy2YWdUyArrxpZCZPikiQBwr8zPXpX5Ck/JSQqEC6ZUw1DPQNNnPXxOsBxTeJwOrcWm+F33yCrbO1TNglDEZZk2xcCQWSSiQJMSNMC12R2DWg+44/3/hgHeUoXmyT6nNWRe0EBwgtJ6vH9rMWXBLD3tYWpCEyu/ngXDCol/bfCpL8uwWWf677EqsiQKa51zf1QlXMpperRBVAtv3E/xDAKsZZWUm3aIlJ4fYu/0gJklIgtEh7zRPSPGd8+4vJiXqfzwek3qfqGMUP6vsusdSb+0Px89mxHyRtiiDEHJETAuL85sgLYICzDrfvAh4H4dpbiLG/CAZxRjUXlTxZk7I4JaGZUUcVVfH7/+d84/Upk/EF/woTtFi3Byy/tIi/y+zEHiY0SMPwyjDvJUD4biD4/pwOgAagkUVbQTzhYMvpVJ5h33jmAr/r88TiWi0BUAZWKUAPxM75lrpA5wAkNqIYWC7bUIY4SG60fiVwb/l8="
        on:
          tags: true
